---
# The driver package pulls in the latest kernel-headers package, but not the
# latest kernel. Check to see if there is a mismatch.

- name: check kernel versions
  yum:
    list: kernel
  register: yum_list

- name: register installed kernel version
  debug:
    msg: "{{ yum_list.results | selectattr('yumstate', 'equalto', 'installed') | list }}"
  register: kernel_version

- name: check kernel-headers versions
  yum:
    list: kernel-headers
  register: yum_list

- name: register installed kernel-headers version
  debug:
    msg: "{{ yum_list.results | selectattr('yumstate', 'equalto', 'installed') | list }}"
  register: kernel_headers_version

- name: update kernel if headers don't match
  yum:
    name:
      - kernel
      - kernel-tools
      - kernel-tools-libs
      - kernel-devel
      - kernel-debug-devel
      - kernel-headers
    state: latest
  register: kernel_update
  when: kernel_version.msg[0].release != kernel_headers_version.msg[0].release
