---
- name: add epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ epel_baseurl }}"
    gpgkey: "{{ epel_gpgkey }}"

- name: install dependencies
  yum:
    name: dkms
    state: latest

- name: add repo
  yum_repository:
    name: cuda
    description: NVIDIA CUDA YUM Repo
    gpgkey: "{{ rhel_cuda_gpgkey }}"
    baseurl: "{{ rhel_cuda_baseurl }}"
